### GET test
GET http://localhost:5000/

### POST /auth/signup
POST http://localhost:5000/auth/signup
Content-Type: application/json

{
  "email": "second@email.com",
  "password": "monPasswordBis",
  "name": "Jane",
  "lastname": "Bond"
}